services:
  postgres:
    image: postgres:16
    container_name: contenedor_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: contenedor_dbeaver
    restart: always
    ports:
      - "8978:8978"
    volumes:
      - dbeaver_data:/opt/cloudbeaver/workspace
    depends_on:
      - postgres

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.0
    container_name: contenedor_dbt
    volumes:
      - ./dbt_proyecto:/usr/app
    environment:
      - DBT_PROFILES_DIR=/usr/app
    working_dir: /usr/app
    depends_on:
      - postgres

  airflow:
    image: apache/airflow:2.9.1-python3.11
    container_name: contenedor_airflow
    restart: always
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./dbt_proyecto:/opt/airflow/dbt_proyecto
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - _PIP_ADDITIONAL_REQUIREMENTS=dbt-postgres psycopg2-binary requests
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DBT_PROFILES_DIR=/opt/airflow/dbt_proyecto
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
      (airflow webserver & airflow scheduler)"
    depends_on:
      - postgres

  metabase:
    image: metabase/metabase:v0.49.3
    container_name: contenedor_metabase
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
  dbeaver_data:
